apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: my-nginx-example #{{ Values.namespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/Sinjebos/helm-argocd-test.git #{{ Values.gitRepo }}
    targetRevision: HEAD
    path: /helmchart/app/templates
    # helm:
    #   values: |
    #     namespace: "my-nginx-example"
    #     gitRepo: "https://github.com/Sinjebos/helm-argocd-test.git"
    #     port: "80"
    #     image: "sinjebos/nginxexample"
    #     tag: "1.0"
  destination: 
    namespace: my-nginx-example #{{ Values.namespace }}
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true