apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx #"{{ .Values.name }}"
spec:
  selector:
    matchLabels:
      app: nginx #"{{ .Values.name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx #"{{ .Values.name }}"
    spec:
      containers:
      - name: nginx #"{{ .Values.name }}"
        image: sinjebos/nginxexample:1.0 #"{{ .Values.image }}":"{{ .Values.tag }}"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx #"{{ .Values.name }}"
spec:
  selector:
    app: nginx #"{{ .Values.name }}"
  ports:
  - port: 80 #"{{ .Values.port }}"
    protocol: TCP
    targetPort: 8085 #"{{ .Values.targetPort }}"